apiVersion: apps/v1 
kind: Deployment                                  
metadata:
  name: {{ .Release.Name }}-web-cve-processor                   
  labels:
    {{- template "labels" .}}
spec:
  replicas: {{ default 1 .Values.replicaCount | int }}                                 
  selector:
    matchLabels: 
      {{- include "labels" . | indent 2}}             
  template:                                      
    metadata:
      labels:                                    
        {{- include "labels" . | indent 4}} 
    spec:         
      initContainers:
      - name: {{ .Release.Name }}-init-web-cve-processor
        image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
        imagePullPolicy: Always 
        volumeMounts:
        - name: config
          mountPath: /config                          
      containers:
      - name: {{ .Release.Name }}-web-cve-processor 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"     
        imagePullPolicy: Always            
        ports:
          - name: http
            containerPort: {{ .Values.service.port | int }}                
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-postgres-secret  
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-liquibase-config
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret            
        