apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-secret
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson  }}