apiVersion: batch/v1
kind: Job                                  
metadata:
  name: {{ .Release.Name }}-web-cve-processor-job
  namespace: {{ .Release.Namespace | quote }}          
  labels:
    {{- template "labels" .}}
spec:           
  template:                                      
    metadata:
      labels:                                    
        {{- include "labels" . | indent 4}} 
    spec:         
      containers:
      - name: {{ .Release.Name }}-web-cve-processor 
        image: "{{ .Values.producerImage.repository }}:{{ .Values.producerImage.tag }}"     
        imagePullPolicy: Always            
        ports:
        - name: http
          containerPort: {{ .Values.service.port | int }}                
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-job-secret
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret
  backoffLimit: 3
         
        
