apiVersion: batch/v1
kind: Job                                  
metadata:
  name: {{ .Release.Name }}-web-cve-processor-job
  namespace: {{ .Values.namespace }}          
  labels:
    {{- template "labels" .}}
spec:           
  template:                                      
    metadata:
      labels:                                    
        {{- include "labels" . | indent 4}} 
    spec:         
      initContainers:
      - name: {{ .Release.Name }}-init-web-cve-processor
        image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
        imagePullPolicy: Always 
        volumeMounts:
        - name: config
          mountPath: "/config/"
      restartPolicy: OnFailure
      containers:
      - name: {{ .Release.Name }}-web-cve-processor 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"     
        imagePullPolicy: Always            
        ports:
        - name: http
          containerPort: {{ .Values.service.port | int }}                
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-postgres-secret
      restartPolicy: OnFailure
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-liquibase-config
            items: 
              - key: "liquibase.properties"
                path: liquibase.properties
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret
  backoffLimit: 3
         
        
