apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Namespace }}-resource-quota
  namespace: {{ .Release.Namespace | quote }} 
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "1024Mi"
    limits.cpu: "750m"
    limits.memory: "1536Mi"
